### ISSUE TITLE
SQLite storage returns roster as an array when it should be a dictionary

### ISSUE THREAD

**Issue by RobertLarsen** [twonds/palaver#8]
...which causes it to fail with this:

```
2013-10-15 16:04:06+0200 [XmlStream,client] Traceback: <type 'exceptions.AttributeError'>: 'list' object has no attribute 'get'
2013-10-15 16:04:06+0200 [XmlStream,client] /media/data/code/palaver/palaver/groupchat.py:765:joinRoom
2013-10-15 16:04:06+0200 [XmlStream,client] /media/data/code/palaver/palaver/groupchat.py:756:get_room
2013-10-15 16:04:06+0200 [XmlStream,client] /usr/lib/python2.7/dist-packages/twisted/internet/defer.py:305:addCallback
2013-10-15 16:04:06+0200 [XmlStream,client] /usr/lib/python2.7/dist-packages/twisted/internet/defer.py:294:addCallbacks
2013-10-15 16:04:06+0200 [XmlStream,client] --- <exception caught here> ---
2013-10-15 16:04:06+0200 [XmlStream,client] /usr/lib/python2.7/dist-packages/twisted/internet/defer.py:576:_runCallbacks
2013-10-15 16:04:06+0200 [XmlStream,client] /media/data/code/palaver/palaver/groupchat.py:727:ret
2013-10-15 16:04:06+0200 [XmlStream,client] /media/data/code/palaver/palaver/groupchat.py:678:getMember
2013-10-15 16:04:06+0200 [XmlStream,client] /media/data/code/palaver/palaver/groupchat.py:342:getMember
```

**Comment by twonds** [comment]
Please test the above fix.

**Comment by RobertLarsen** [comment]
I will try it. However, seems I haven't kept my working copy up to date. Something broke between bbba27ddd595fc43fd266c6aa2b071ba8bff7de6 and 92156eaf10aa6931adc0a4c58a4e062652d918d4.

I get this (on master):

```
$ twistd --nodaemon --python palaver.tac 
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 652, in run
    runApp(config)
  File "/usr/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 386, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 451, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 462, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/application/service.py", line 405, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "palaver.tac", line 36, in <module>
    c = IService(bs)
exceptions.TypeError: ('Could not adapt', <palaver.groupchat.GroupchatService instance at 0x2df3d88>, <InterfaceClass twisted.words.protocols.jabber.ijabber.IService>)

Failed to load application: ('Could not adapt', <palaver.groupchat.GroupchatService instance at 0x2df3d88>, <InterfaceClass twisted.words.protocols.jabber.ijabber.IService>)
```

**Comment by twonds** [comment]
Yeah, I need to start creating branches for some of these changes. The above commit should fix it.

**Comment by RobertLarsen** [comment]
Getting close :-)
But there is another list-believed-to-be-dictionary bug:

```
2013-10-16 20:26:37+0200 [XmlStream,client] Traceback: <type 'exceptions.AttributeError'>: 'list' object has no attribute 'has_key'
2013-10-16 20:26:37+0200 [XmlStream,client] /media/data/code/palaver/palaver/groupchat.py:765:joinRoom
2013-10-16 20:26:37+0200 [XmlStream,client] /media/data/code/palaver/palaver/groupchat.py:756:get_room
2013-10-16 20:26:37+0200 [XmlStream,client] /usr/lib/python2.7/dist-packages/twisted/internet/defer.py:305:addCallback
2013-10-16 20:26:37+0200 [XmlStream,client] /usr/lib/python2.7/dist-packages/twisted/internet/defer.py:294:addCallbacks
2013-10-16 20:26:37+0200 [XmlStream,client] --- <exception caught here> ---
2013-10-16 20:26:37+0200 [XmlStream,client] /usr/lib/python2.7/dist-packages/twisted/internet/defer.py:576:_runCallbacks
2013-10-16 20:26:37+0200 [XmlStream,client] /media/data/code/palaver/palaver/groupchat.py:739:ret
2013-10-16 20:26:37+0200 [XmlStream,client] /media/data/code/palaver/palaver/groupchat.py:683:checkBanned
2013-10-16 20:26:37+0200 [XmlStream,client] /media/data/code/palaver/palaver/groupchat.py:394:checkBanned
```

This is when using the sqlite storage.

**Comment by twonds** [comment]
Try again :)

**Comment by RobertLarsen** [comment]
NICE!!
Thanks.
